################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_gap_aci.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_gatt_aci.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_hal_aci.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_l2cap_aci.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_utils.c 

OBJS += \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_gap_aci.o \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_gatt_aci.o \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_hal_aci.o \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_l2cap_aci.o \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_utils.o 

C_DEPS += \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_gap_aci.d \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_gatt_aci.d \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_hal_aci.d \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_l2cap_aci.d \
./Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_utils.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_gap_aci.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_gap_aci.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_gap_aci.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_gatt_aci.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_gatt_aci.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_gatt_aci.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_hal_aci.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_hal_aci.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_hal_aci.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_l2cap_aci.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_l2cap_aci.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_l2cap_aci.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_utils.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/hci/controller/bluenrg_utils.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Middlewares/STM32_BlueNRG/HCI/Controller/bluenrg_utils.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


