################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c 

OBJS += \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.o 

C_DEPS += \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_adc_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_spi.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_uart.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


