################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_accelero.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_gyro.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_magneto.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_pressure.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_temperature.c 

OBJS += \
./Drivers/Board/steval_fcu001_v1.o \
./Drivers/Board/steval_fcu001_v1_accelero.o \
./Drivers/Board/steval_fcu001_v1_gyro.o \
./Drivers/Board/steval_fcu001_v1_magneto.o \
./Drivers/Board/steval_fcu001_v1_pressure.o \
./Drivers/Board/steval_fcu001_v1_temperature.o 

C_DEPS += \
./Drivers/Board/steval_fcu001_v1.d \
./Drivers/Board/steval_fcu001_v1_accelero.d \
./Drivers/Board/steval_fcu001_v1_gyro.d \
./Drivers/Board/steval_fcu001_v1_magneto.d \
./Drivers/Board/steval_fcu001_v1_pressure.d \
./Drivers/Board/steval_fcu001_v1_temperature.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/Board/steval_fcu001_v1.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/Board/steval_fcu001_v1.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/Board/steval_fcu001_v1_accelero.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_accelero.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/Board/steval_fcu001_v1_accelero.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/Board/steval_fcu001_v1_gyro.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_gyro.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/Board/steval_fcu001_v1_gyro.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/Board/steval_fcu001_v1_magneto.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_magneto.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/Board/steval_fcu001_v1_magneto.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/Board/steval_fcu001_v1_pressure.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_pressure.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/Board/steval_fcu001_v1_pressure.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/Board/steval_fcu001_v1_temperature.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Drivers/BSP/STEVAL_FCU001_V1/steval_fcu001_v1_temperature.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/Board/steval_fcu001_v1_temperature.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


