################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/ahrs.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/basic_math.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/console.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/debug.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/flight_control.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/main.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/motor.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/quaternion.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/rc.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/sensor_data.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/sensor_service.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/stm32f4xx_hal_msp.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/stm32f4xx_it.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/timer.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/usb_device.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/usbd_cdc_if.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/usbd_conf.c \
/Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/usbd_desc.c 

OBJS += \
./Application/User/ahrs.o \
./Application/User/basic_math.o \
./Application/User/console.o \
./Application/User/debug.o \
./Application/User/flight_control.o \
./Application/User/main.o \
./Application/User/motor.o \
./Application/User/quaternion.o \
./Application/User/rc.o \
./Application/User/sensor_data.o \
./Application/User/sensor_service.o \
./Application/User/stm32f4xx_hal_msp.o \
./Application/User/stm32f4xx_it.o \
./Application/User/timer.o \
./Application/User/usb_device.o \
./Application/User/usbd_cdc_if.o \
./Application/User/usbd_conf.o \
./Application/User/usbd_desc.o 

C_DEPS += \
./Application/User/ahrs.d \
./Application/User/basic_math.d \
./Application/User/console.d \
./Application/User/debug.d \
./Application/User/flight_control.d \
./Application/User/main.d \
./Application/User/motor.d \
./Application/User/quaternion.d \
./Application/User/rc.d \
./Application/User/sensor_data.d \
./Application/User/sensor_service.d \
./Application/User/stm32f4xx_hal_msp.d \
./Application/User/stm32f4xx_it.d \
./Application/User/timer.d \
./Application/User/usb_device.d \
./Application/User/usbd_cdc_if.d \
./Application/User/usbd_conf.d \
./Application/User/usbd_desc.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/ahrs.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/ahrs.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/ahrs.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/basic_math.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/basic_math.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/basic_math.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/console.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/console.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/console.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/debug.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/debug.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/debug.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/flight_control.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/flight_control.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/flight_control.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/main.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/main.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/motor.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/motor.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/motor.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/quaternion.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/quaternion.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/quaternion.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/rc.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/rc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/rc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/sensor_data.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/sensor_data.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/sensor_data.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/sensor_service.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/sensor_service.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/sensor_service.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/stm32f4xx_hal_msp.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/stm32f4xx_hal_msp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/stm32f4xx_hal_msp.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/stm32f4xx_it.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/stm32f4xx_it.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/stm32f4xx_it.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/timer.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/timer.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/usb_device.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/usb_device.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/usb_device.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/usbd_cdc_if.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/usbd_cdc_if.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/usbd_cdc_if.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/usbd_conf.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/usbd_conf.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/usbd_conf.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Application/User/usbd_desc.o: /Users/Alberic/Downloads/ST_Drone_FCU_F401-master\ 2/STM32\ FW\ Project/Official\ release\ with\ BLE\ Remocon\ -\ 170318/Src/usbd_desc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DUSE_HAL_DRIVER -DSTM32F401xC -DDEBUG -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Board" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis3mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps25hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/Common" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm6dsl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lps22hb" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lsm303agr" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/STEVAL_FCU001_V1" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/lis2mdl" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/Users/Alberic/Downloads/ST_Drone_FCU_F401-master 2/STM32 FW Project/Official release with BLE Remocon - 170318/Drivers/BSP/Components/spbtlerf"  -O0 -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Application/User/usbd_desc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


